site_name: Pyschool-lib Documentation
repo_url: https://github.com/darko-itpro/pyschool-lib
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
nav:
  - Home: index.md
  - Packaging: package.md
  - Documentation des packages:
    - api/index.md
    - pyflix.datasource: api/pyflixdatasource.md
    - pyflix.utils: api/utils.md
    - pyflix.loaders: api/loaders.md
theme:
  name: material
  features:
    - navigation.indexes
